version: '3'

services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - MONGO_URI: mongodb://db:27017/database-api-github

  client:
    build: ./client
    ports:
      - "3000:3000"

  db:
    image: mongo
    ports:
      - "27017:27017"