version: '3'

services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    
  api:
    container_name: api
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"